# Generated by Django 6.0.6 on 2026-06-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='ordered', max_length=20),
        ),
    ]
